server:
  port: 18181
  servlet:
    context-path: /monolith # Если этот параметр указываем, то его нужно включить в маршрут(ы) в PrefixPath. Например: «- PrefixPath=/monolith/api/v1». При этом в контроллер всё равно придут только /api/vi/….

spring:
  application:
    name: monolith-module
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect #org.hibernate.dialect.H2Dialect #
    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false

# ___________________________________________________________
# Следующие свойства загружаются на «этапе @PostConstruct».
app:
  product:
    price:
      min: 0.01
      #max: 9999999.99 #если перед запятой >7 знаков, то число считывается в эксп.виде: 1.999999999E7.
views:
  shop:
    page:
      items: 6

