//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 02:15:55 AM MSK 
//


package temp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fromId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="toId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromId",
    "toId"
})
@XmlRootElement(name = "getProductSoapRangeByIdRequest")
public class GetProductSoapRangeByIdRequest {

    protected long fromId;
    protected long toId;

    /**
     * Gets the value of the fromId property.
     * 
     */
    public long getFromId() {
        return fromId;
    }

    /**
     * Sets the value of the fromId property.
     * 
     */
    public void setFromId(long value) {
        this.fromId = value;
    }

    /**
     * Gets the value of the toId property.
     * 
     */
    public long getToId() {
        return toId;
    }

    /**
     * Sets the value of the toId property.
     * 
     */
    public void setToId(long value) {
        this.toId = value;
    }

}
