//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 02:15:55 AM MSK 
//


package temp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the temp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: temp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductSoapByIdRequest }
     * 
     */
    public GetProductSoapByIdRequest createGetProductSoapByIdRequest() {
        return new GetProductSoapByIdRequest();
    }

    /**
     * Create an instance of {@link GetProductSoapByIdResponse }
     * 
     */
    public GetProductSoapByIdResponse createGetProductSoapByIdResponse() {
        return new GetProductSoapByIdResponse();
    }

    /**
     * Create an instance of {@link ProductSoap }
     * 
     */
    public ProductSoap createProductSoap() {
        return new ProductSoap();
    }

    /**
     * Create an instance of {@link GetProductSoapRangeByIdRequest }
     * 
     */
    public GetProductSoapRangeByIdRequest createGetProductSoapRangeByIdRequest() {
        return new GetProductSoapRangeByIdRequest();
    }

    /**
     * Create an instance of {@link GetProductSoapRangeByIdResponse }
     * 
     */
    public GetProductSoapRangeByIdResponse createGetProductSoapRangeByIdResponse() {
        return new GetProductSoapRangeByIdResponse();
    }

}
