server:
  port: 22854
  servlet:
    context-path: /market-order

integration:
  product-service:
    url: http://localhost:18181/market-monolith
  user-service:
    url: http://localhost:18181/market-monolith
  cart-service:
    url: http://localhost:8191/market-cart

spring: # < конфигурируем спринг-окружение
  datasource: # < спринговый стандартный бин для подключения к базе данных
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: postgres

  jpa: # < указываем реализацию JPA (по умолчанию будет подключен хибер-т)
    show-sql: true # < показывать сгенерированные запросы хибер-та
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.PostgreSQL94Dialect #
    open-in-view: false #(j7-10)

  h2: # < необязательная настройка БД (Спринг дружит с h2 и позволяет делать такую настройку)
    console:
      enabled: true # < ?кажется, поддержка консольного ввода для работы с БД?
      settings:
        web-allow-others: false # < закрыть доступ к этой консоли из других WEB-приложений (только из браузера можно)
