server:
  port: 22854
  servlet:
    context-path: /order

integration:
  product-service:
    url: http://localhost:18181/monolith
  user-service:
    url: http://localhost:7777/ouruser
  cart-service:
    url: http://localhost:8191/cart

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect #org.hibernate.dialect.H2Dialect #
    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
