server:
  port: 8191
  servlet:
    context-path: /cart

integration:
  product-service:
    url: http://localhost:18181/monolith
  user-service:
    url: http://localhost:7777/ouruser

spring:
  application:
    name: cart-service

# ___________________________________________________________
# Следующие свойства загружаются на «этапе @PostConstruct».
app:
  cart:
    prefix: 'GB_RU_J7_WEBSHOP_V2_'
    life: 130
